const TYPE_LOGIN = 'TYPE_LOGIN';
const TYPE_LOGIN_FACEBOOK = 'TYPE_LOGIN_FACEBOOK';
const TYPE_AUTH_CHANGE = 'TYPE_AUTH_CHANGE';
const TYPE_CREATE_USER = 'TYPE_CREATE_USER';

const TYPE_REQUEST_BEERS = 'TYPE_REQUEST_BEERS';
const TYPE_SAVE_BEER = 'TYPE_SAVE_BEER';

const TYPE_REQUEST_BEERS_FROM_USER = 'TYPE_REQUEST_BEERS_FROM_USER';
const TYPE_SAVE_BEER_FROM_USER = 'TYPE_SAVE_BEER_FROM_USER';
const TYPE_DELETE_BEER_FROM_USER = 'TYPE_DELETE_BEER_FROM_USER';

const TYPE_REQUEST_PICTURE = 'TYPE_REQUEST_PICTURE';
const TYPE_UPLOAD_PICTURE = 'TYPE_UPLOAD_PICTURE';

const TYPE_REQUEST_TYPES = 'TYPE_REQUEST_TYPES';
const TYPE_SAVE_TYPES = 'TYPE_SAVE_TYPES';
const TYPE_ERROR = 'TYPE_ERROR';
const TYPE_LOADING = 'TYPE_LOADING';

export {
  TYPE_LOGIN,
  TYPE_LOGIN_FACEBOOK,
  TYPE_AUTH_CHANGE,
  TYPE_CREATE_USER,
  TYPE_REQUEST_BEERS,
  TYPE_SAVE_BEER,
  TYPE_REQUEST_BEERS_FROM_USER,
  TYPE_SAVE_BEER_FROM_USER,
  TYPE_DELETE_BEER_FROM_USER,
  TYPE_REQUEST_PICTURE,
  TYPE_UPLOAD_PICTURE,
  TYPE_REQUEST_TYPES,
  TYPE_SAVE_TYPES,
  TYPE_ERROR,
  TYPE_LOADING,
}