const TYPE_LOGIN = 'TYPE_LOGIN';
const TYPE_LOGIN_FACEBOOK = 'TYPE_LOGIN_FACEBOOK';
const TYPE_AUTH_CHANGE = 'TYPE_AUTH_CHANGE';
const TYPE_REQUEST_BEERS = 'TYPE_REQUEST_BEERS';
const TYPE_SAVE_BEER = 'TYPE_SAVE_BEER';
const TYPE_DELETE_BEER = 'TYPE_DELETE_BEER';
const TYPE_REQUEST_BEERS_FROM_USER = 'TYPE_REQUEST_BEERS_FROM_USER';
const TYPE_ERROR = 'TYPE_ERROR';
const TYPE_LOADING = 'TYPE_LOADING';

export {
  TYPE_LOGIN,
  TYPE_LOGIN_FACEBOOK,
  TYPE_AUTH_CHANGE,
  TYPE_REQUEST_BEERS,
  TYPE_SAVE_BEER,
  TYPE_DELETE_BEER,
  TYPE_REQUEST_BEERS_FROM_USER,
  TYPE_ERROR,
  TYPE_LOADING,
}